FROM arm64v8/python:3.11.2-alpine3.17

# Install necessary packages
RUN apk update && \
    apk add --no-cache nano sudo shadow

# Add a user for running the app
RUN adduser -D -s /bin/bash flaskuser

# Add flaskuser to sudoers
RUN echo 'flaskuser ALL=(ALL) NOPASSWD: /sbin/reboot' >> /etc/sudoers

USER flaskuser

# Copy application files
COPY . /app
WORKDIR /app

# Install dependencies
RUN pip install -r requirements.txt

# Expose the application port
EXPOSE 5000

# Run the Flask application
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]
