#FROM python:3.7-alpine
#FROM arm32v7/alpine:3.12
#FROM arm32v6/python:3.7.9-alpine3.12
FROM arm64v8/python:3.11.2-alpine3.17


# Install sudo and other necessary packages
RUN apk update && \
    apk add --no-cache nano sudo

# Create a non-root user and allow it to use sudo without a password
RUN adduser -D appuser && \
    echo "appuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to the non-root user
USER appuser

COPY requirements.txt /
RUN pip install -r requirements.txt

COPY . app
WORKDIR /app

ENV FLASK_APP /app.py
CMD gunicorn --bind 0.0.0.0:5000 wsgi:app

EXPOSE 5000
