apiVersion: 1

datasources:
- name: InfluxDB_v2_Flux
  type: influxdb
  access: proxy
  url: http://localhost:8086
  jsonData:
    version: Flux
    organization: jokley
    defaultBucket: jokley_bucket
    tlsSkipVerify: true
  secureJsonData:
    token: jokley
# - name: "JSON_API"
#   type: marcusolsson-json-datasource
#   #url: http://flask-api:5000/WK_Dashboard
#   #url: http://wk-dashboard-backend-dev/WK_Dashboard
#   url: $BACKEND_URL
#   isDefault: false
#   version: 1
#   readOnly: true
# - name: Environment
#   type: volkovlabs-env-datasource
#   access: proxy
#   isDefault: true
#   orgId: 1
#   version: 1
#   editable: true
#   jsonData:
#     filter: FRONTEND_URL